### ISSUE TITLE
Can't seem to use this plugin with metalsmith-in-place

### ISSUE THREAD

**Issue by Davoleo** [tests-always-included/metalsmith-data-loader#22] opened 2021-07-05 16:18 UTC
Hi, I'm trying to extract data from templates in my project, I'm currently using [metalsmith-in-place](https://github.com/metalsmith/metalsmith-in-place) to compile Handlebars templates into themselves, and while this works perfectly using YAML Frontmatter it stops working when I try to use this plugin to inject external data into the template, 

Side note: yes, I am running this plugin before in-place since YAML frontmatter needs to be injected before the other plugin tries to parse it

From the docs in the README and examples I'm taking that this plugin replaces data from data files into templates directly, or am I using it the wrong way?

Data File
```yaml
title: More Links

hasScript: false

links:
- name: Projects
  url: projects.html
- name: Donations
  url: donate.html
- name: PC Config
  url: pc.html
- name: AWC Badges
  url: awc.html
```

Template
```hbs
---
filename: more
data: "/data/more.yaml"
---
<!DOCTYPE html>
<html lang="en">

{{> header}}

<body>
{{> back_button}}

<div class="container-fluid">
  <h1 class="glow-anim">{{title}}</h1>
  <div id="link_container">
    {{#each links}}
    <a href="{{this.url}}" class="button-link">{{this.name}}</a>
    {{/each}}
  </div>
</div>

<script src="js/main.js" type="text/javascript"></script>
<script src="js/projects.js" type="text/javascript"></script>
</body>
</html>
```

Metalsmith Configuration
```js
const Metalsmith = require("metalsmith");

//Handlebars templates and SCSS
const templates = require("metalsmith-in-place");
const sass = require("metalsmith-sass");
const dataLoader = require("metalsmith-data-loader");
const fs = require('fs');
const Handlebars = require('handlebars');

// ... more code here ...

const smithInstance = Metalsmith(__dirname)
    .source("src")
    .destination("dist")
    .metadata({
        author: "Davoleo",
        site: "https://davoleo.net"
    })
    .use(dataLoader({
        dataProperty: "data",
        removeSource: true,
        match: "*.{hbs,html}"
    }))
    .use(templates({
        pattern: '*.{hbs,handlebars}',
    }))
    .use(sass({
        outputStyle: "expanded",
        outputDir: "css/",
        sourceMaps: true,
        sourceMapsContents: true
    }));
```

**Comment by fidian** [comment] 2021-07-12 14:58
Your example left a few things to guesswork, such as where the files are placed and how handlebars gets called. I've trimmed down the example to show how it works.

`package.json`
```
{
    "private": true,
    "dependencies": {
        "handlebars": "^4.7.7",
        "metalsmith": "^2.3.0",
        "metalsmith-data-loader": "^1.1.5",
        "metalsmith-handlebars-contents": "^1.1.0",
        "metalsmith-in-place": "^4.4.2",
        "metalsmith-sass": "^1.7.0"
    }
}
```

`metalsmith.js` with some minor changes and debugging.
```
#!/usr/bin/env node
const Metalsmith = require("metalsmith");

const dataLoader = require("metalsmith-data-loader");
const fs = require('fs');
const handlebars = require("metalsmith-handlebars-contents")

const smithInstance = Metalsmith(__dirname)
    .source("src")
    .destination("dist")
    .metadata({
        author: "Davoleo",
        site: "https://davoleo.net"
    })
    .use(displayFile('Before processing'))
    .use(dataLoader({
        dataProperty: "data",
        removeSource: true,
        match: "*.{hbs,html}"
    }))
    .use(handlebars({
        match: "*.{hbs,html}"
    }))
    .use(displayFile('After processing'))
    .build(function (err) {
        if (err) {
            console.error(err);
        } else {
            console.log('Build complete');
        }
    });

function displayFile(label) {
    return function (files, metalsmith, done) {
        console.log(label);
        Object.entries(files['more.html']).forEach(function (entry) {
            switch (entry[0]) {
                case 'stats':
                    break;

                case 'contents':
                    console.log(entry[0] + ":");
                    console.log(entry[1].toString());
                    break;

                default:
                    console.log(entry[0] + ":", entry[1]);
            }
        });
        done();
    };
}
```

`src/more.html` with extra HTML removed and the `#each` tag modified to iterate over the `data` property.
```
---
filename: more
data: "/data/more.yaml"
---
    {{#each data.links}}
    <a href="{{this.url}}" class="button-link">{{this.name}}</a>
    {{/each}}
```

`src/data/more.yaml`
```
title: More Links

hasScript: false

links:
- name: Projects
  url: projects.html
- name: Donations
  url: donate.html
- name: PC Config
  url: pc.html
- name: AWC Badges
  url: awc.html
```

When running, you will see the file before the data is loaded and before handlebars is applied, then you will see the file after both have done their work on the file.

```
Before processing
filename: more
data: /data/more.yaml
contents:
    {{#each data.links}}
    <a href="{{this.url}}" class="button-link">{{this.name}}</a>
    {{/each}}

mode: 0664
After processing
filename: more
data: {
  title: 'More Links',
  hasScript: false,
  links: [
    { name: 'Projects', url: 'projects.html' },
    { name: 'Donations', url: 'donate.html' },
    { name: 'PC Config', url: 'pc.html' },
    { name: 'AWC Badges', url: 'awc.html' }
  ]
}
contents:
    <a href="projects.html" class="button-link">Projects</a>
    <a href="donate.html" class="button-link">Donations</a>
    <a href="pc.html" class="button-link">PC Config</a>
    <a href="awc.html" class="button-link">AWC Badges</a>

mode: 0664
Build complete
```

Notice how the `data` property in the top half will refer to the filename and in the bottom half it shows the data included from the YAML file.

**Comment by fidian** [comment] 2021-07-12 14:59
I am going to close this issue because I believe this example shows how everything works. If this is not the case, please provide a full sample repository that illustrates the problem - one the builds, has templates, and includes everything needed to show that it should work. Most likely the problem is that you are iterating over the wrong property in the HTML to generate the links.

**Closed as completed** 2021-07-12 15:01 UTC

**Comment by Davoleo** [comment] 2021-07-13 13:55
You're totally right I could've just shared my repository, and it would have been way easier for you to find out what's wrong (which btw is https://github.com/Davoleo/davoleo.github.io), in your example you're using `metalsmith-handlebars-content` instead of `metalsmith-in-place` which in my case is the one that calls Handlebars, while I handle partials and helpers manually right now, if that plugin allows the same thing with better integration with data loading I'll gladly switch over to the other plugin.

Also many thanks for the example metalsmith middleware you've created on the fly to display files, it will certainly help me figure out more how all of this works and also to build plugins myself if I ever need to, thank you, really!

EDIT: Ok, I've tried out `handlebars-content` but the output extension doesn't seem to be updated to be `.html` and remains `.hbs` despite the templates being filled and compiled correctly, I would need to write a renamer that takes hbs extensions and changes them to `.html`
